services:
  # 1. PostgreSQL Database Service
  postgres:
    image: postgres:14-alpine
    container_name: shambasure-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: shambasure
      POSTGRES_USER: shambasure
      POSTGRES_PASSWORD: shambasure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shambasure-net

  # 2. RabbitMQ Message Broker Service
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: shambasure-rabbitmq
    ports:
      - '5672:5672' # Port for the backend to connect
      - '15672:15672' # Port for the web management UI
    networks:
      - shambasure-net
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  postgres-data:

networks:
  shambasure-net:
